name: odm_ui
description: OnDaMenu interface for mobile UI and POS UI

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # original: sdk: ">=2.7.0 <3.0.0"
  # latest:
  sdk: ">=2.12.0 <3.3.2"



dependencies:
  flutter:
    sdk: flutter


  # original
  # latest:
  cupertino_icons: ^1.0.2
  # original: cupertino_icons: ^0.1.3

  # firebase dependencies
  # origingl: firebase_core: "0.7.0"
  # latest:
  firebase_core: "^1.10.2"
  # base git: firebase_core: "0.5.0"

  # original: firebase_auth: "^1.1.0"
  # latest:
  firebase_auth: ^3.10.0
  firebase_auth_web: ^4.5.0

  http: ^0.13.4
  http_parser: ^4.0.0
  # base git: firebase_auth: "^0.18.0+1"

  # google fonts
  # original: google_fonts: ^1.1.2
  # base git:
  google_fonts: ^3.0.1

  # flutter_svg:
  flutter_svg: ^1.1.5
  fl_chart: ^0.55.1
  provider: ^6.0.3

  # cloud firestore_ui:
  # base git: cloud_firestore: "^0.14.0+2"
  # cloud_firestore: "^0.14.1"
  # latest:
  cloud_firestore: ^3.1.5

  # BLoC Data Seperation
  flutter_bloc: ^8.0.0

  # Equatable
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  ### flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

