// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgMX-1NZ-J8287OkDkBHFcJChrJr_IRaQ',
    appId: '1:1024532317222:web:44dbb556f20fe998e412e7',
    messagingSenderId: '1024532317222',
    projectId: 'ondamenu-pos',
    authDomain: 'ondamenu-pos.firebaseapp.com',
    databaseURL: 'https://ondamenu-pos-default-rtdb.firebaseio.com',
    storageBucket: 'ondamenu-pos.appspot.com',
    measurementId: 'G-L2XVZWQYST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWjeIjGY_9B1m6JhT7Tkt2AtvRtiW8mk',
    appId: '1:1024532317222:android:c8cd7594f341f563e412e7',
    messagingSenderId: '1024532317222',
    projectId: 'ondamenu-pos',
    databaseURL: 'https://ondamenu-pos-default-rtdb.firebaseio.com',
    storageBucket: 'ondamenu-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkG6no-9e7Z9MYgd39Yzw5CCunIaSN0aE',
    appId: '1:1024532317222:ios:4d5ef57fd47bac9fe412e7',
    messagingSenderId: '1024532317222',
    projectId: 'ondamenu-pos',
    databaseURL: 'https://ondamenu-pos-default-rtdb.firebaseio.com',
    storageBucket: 'ondamenu-pos.appspot.com',
    iosClientId: '1024532317222-r7ft01ntg72a0q6k62lrlrhsh2oifaju.apps.googleusercontent.com',
    iosBundleId: 'com.example.odmUi',
  );
}
